### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ghost** [git-developer/ti-cc-tool#10]
I keep on getting this error when running the docker command or the docker-compose command

 `could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'` 
 
 - My Sonoff device permissions are 777 currently 
 - I've tried running docker with --privilege combined with sudo with no luck either
 
 Nothing seems to work. Please help. Thanks so much for putting this together.

**Comment by git-developer** [comment]
Who is owner of your device on the host?
```
$ ls -al /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 0  8. Mär 04:17 /dev/ttyUSB0
```

Who is owner of your device in the container?
```
$ docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --entrypoint /bin/sh ckware/ti-cc-tool -c 'ls -la /dev/ttyUSB0'
crw-rw----    1 root     dialout   188,   0 Apr 15 04:42 /dev/ttyUSB0
```

What groups does your user belong to on the host and in the container?
```
$ id
uid=1000(user) gid=1000(user) groups=1000(user),20(dialout),100(users),996(docker)

$ docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --entrypoint /bin/sh ckware/ti-cc-tool -c 'id'
uid=1000(user) gid=1000(user) groups=20(dialout)
```

**Comment by git-developer** [comment]
@coinerrr Please run the commands above and post the output here if the problem still occurs.

**Comment by Qonstrukt** [comment]
I'm facing the same issue, for some reason the device belongs to the `audio` group in Docker:
```
# docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --entrypoint /bin/sh ckware/ti-cc-tool -c 'ls -la /dev/ttyUSB0'
crw-rw----    1 root     audio     188,   0 Apr 20 13:23 /dev/ttyUSB0
```

Could be because of my non-standard linux distribution perhaps. (LibreELEC)

I'm starting the container as root, in the container I'm part of the dialout group:
```
# docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --entrypoint /bin/sh ckware/ti-cc-tool -c 'id'
uid=1000(user) gid=1000(user) groups=20(dialout),1000(user)
```

I can work around it by running `chmod 666` on it of course, but maybe interesting to fix for some more exotic configuration. 😊

**Comment by git-developer** [comment]
> for some reason the device belongs to the `audio` group in Docker

Group `audio` in the container has gid 18. Probably your `/dev/ttyUSB0` belongs to a group with gid 18 on the host. You could try to add this group to the docker user by adding `--group-add 18` to the docker arguments, e.g.
```
# docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --group-add 18 ...
```

**Comment by git-developer** [comment]
Or, more generic:
```
# docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --group-add "$(stat --format=%g /dev/ttyUSB0)" ...
```

**Comment by git-developer** [comment]
Please report back if this helps. The documentation could then be updated for operating systems that do not use gid 20 for group dialout.

**Comment by git-developer** [comment]
@coinerrr, @Qonstrukt Please report back if adding `--group-add "$(stat --format=%g /dev/ttyUSB0)"` solves your problem.

**Comment by zaubara** [comment]
For me, stat had to use the format "stat -c %g /dev/ttyUSB0", but otherwise that worked like a charm :) With that, updating from within Home Assistant OS worked perfectly fine. (I used the Advanced SSH & Web Terminal plugin, since the dedicated plugin wouldn't work)
