### ISSUE TITLE
Error "docker: unknown server OS: ."

### ISSUE THREAD

**Issue by jeroen85** [git-developer/ti-cc-tool#2]
Hi, I would really like to use this tool. Would be much easer than removing stick from my NAS and perform update on my laptop.

I tried to run this on my Synology NAS (DS218+, which features an Intel CPU (Intel Celeron J3355, Apollolake)), but got the following error:

```
docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 -e FIRMWARE_URL=https://github.com/Koenkk/Z-Stack-firmware/raw/develop/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20221102.zip ckware/ti-cc-tool -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb
docker: unknown server OS: .
```

Any advice?

**Comment by jeroen85** [comment]
Solved... I feel stupid ;-)
Had to use `sudo docker run...`

After this it did the update without any issues. Thanks for your work!

**Comment by git-developer** [comment]
You're welcome!
