### ISSUE TITLE
ERROR: Download of firmware was not successful

### ISSUE THREAD

**Issue by glynhudson** [git-developer/ti-cc-tool#4]
Hi, I'm having issues running the script. I've tested on both RaspberryPi and Ubuntu desktop 22.04. I get the same error each time. 

The URL in the command is correct, any idea why the FW download is failing? 

```
docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 -e FIRMWARE_URL=https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20220219.zip ckware/ti-cc-tool -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb
Unable to find image 'ckware/ti-cc-tool:latest' locally
latest: Pulling from ckware/ti-cc-tool
c158987b0551: Pull complete 
cd0cef17304a: Pull complete 
8dd1360d2e23: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:7f4d3c6ea6e0d65517da9267f76d22bf468c9e5bcc4efcb96f3f99fcd4980cd0
Status: Downloaded newer image for ckware/ti-cc-tool:latest
Downloading firmware from https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20220219.zip
ERROR: Download of firmware was not successful.
```

**Comment by glynhudson** [comment]
I've just tested on a newer version of docker (Docker version 24.0.1) on ubuntu 22.04, and it worked! :+1: 

The issue must be the older version of docker on the RaspberryPi (Docker version 20.10.18)

**Comment by git-developer** [comment]
The regular image [requires](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements) at least Docker 19.03.9 and libseccomp 2.4.2. There's a legacy image `ckware/ti-cc-tool:legacy-latest` for incompatible hosts (see #3).

**Comment by glynhudson** [comment]
Interesting, so it *should* have worked on docker 20.10.18? This issue must be something else?

**Comment by git-developer** [comment]
I suffered from this issue a few times, the problem was always libseccomp being too old. Maybe you can find out the previous and current version of this library on the affected system (see `/var/log/apt/history.log`)?

**Comment by glynhudson** [comment]
Ah on the effected system libseccomp was an older version:  2.3.3-4 

```
dpkg -l | grep libseccomp
ii  libseccomp2:armhf                2.3.3-4 
```
