### ISSUE TITLE
Unreadble firmware file

### ISSUE THREAD

**Issue by yayitazale** [git-developer/ti-cc-tool#5]
Hi, I have this error:

```
root@Tower:~# docker run -e FIRMWARE_FILE="https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20221226.zip" --device=/dev/ttyUSB0 ckware/ti-cc-tool -ewv "fw-file"
ERROR: Unreadable firmware file 'https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20221226.zip'
```

I'm using this for 2nd time, the first time was 1 year ago and worked good. I'm using the same command, so I don't know what changed or I'm doing wrong.

Thanks!

**Comment by git-developer** [comment]
Did you mix up `FIRMWARE_FILE` with `FIRMWARE_URL`?

**Comment by yayitazale** [comment]
> Did you mix up `FIRMWARE_FILE` with `FIRMWARE_URL`?

My fault sorry
