### ISSUE TITLE
Failed to flash: Not a multiple of 4

### ISSUE THREAD

**Issue by galmok** [git-developer/ti-cc-tool#6]
I tried to use this docker image to flash my cc2562 device with this firmware:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip

and it failed:

```
Unable to find image 'ckware/ti-cc-tool:latest' locally
latest: Pulling from ckware/ti-cc-tool
261da4162673: Pull complete
507a68f54c5a: Pull complete
8bdc970eb54e: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:7f4d3c6ea6e0d65517da9267f76d22bf468c9e5bcc4efcb96f3f99fcd4980cd0
Status: Downloaded newer image for ckware/ti-cc-tool:latest
Downloading firmware from https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip
Firmware file:   'CC2652RB_coordinator_20230507.zip'
Opening port /dev/ttyUSB0, baud 500000
Reading data from CC2652RB_coordinator_20230507.zip
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:25:XX:XX:XX
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 125878 bytes starting at address 0x00000000
ERROR: Invalid data size: 125878. Size must be a multiple of 4.
```

Pretty annoying that it didn't check the hex file prior to erasing the device(!)

I managed to flash the firmware using ZigStart multi tool instead:

https://zig-star.com/radio-docs/zigstar-multi-tool/

**Comment by git-developer** [comment]
The URL points to a JSON file. Did you mix up the URL

`https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip`

with

`https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip`?

> Pretty annoying that it didn't check the hex file prior to erasing the device(!)

I agree and recommend to report this issue in the repository that contains the code to flash a device: [JelmerT/cc2538-bsl](https://github.com/JelmerT/cc2538-bsl).

**Comment by galmok** [comment]
It does look like I got the URL mixed up, yes. As I have made the flash using zigstar, I have solved my immediate problem and will not reflash this device right now. Thank you for looking into this so fast.
