### ISSUE TITLE
RF-Star RF-DG-52PAS

### ISSUE THREAD

**Issue by chris-1243** [git-developer/ti-cc-tool#7]
Hello,

I am trying to update a RF-Star RF-DG-52PAS based on TI CC2652P chip with your project. When I start my compose file, I receive suche error:

```
[+] Running 1/0
 ✔ Container firmware_update-ti-cc-tool-1  Created                                                                 0.1s
Attaching to ti-cc-tool-1
ti-cc-tool-1  | Firmware file:   '/firmware.hex'
ti-cc-tool-1  | Opening port /dev/ttyUSB0, baud 500000
ti-cc-tool-1  | Reading data from /firmware.hex
ti-cc-tool-1  | Firmware file: Intel Hex
ti-cc-tool-1  | Connecting to target...
ti-cc-tool-1  | ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'
ti-cc-tool-1 exited with code 1
``` 

I check my adapter is well connected to `/dev/ttyUSB0` by checking with this command `ls -l /dev/serial/by-id` and here is the output:
```
lrwxrwxrwx 1 root root 13 Feb 29 11:23 usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB0
``` 

My docker-compose.yaml 

```dockerfile
services:
  ti-cc-tool:
    image: "ckware/ti-cc-tool"
    environment:
      #FIRMWARE_FILE: "/firmware.zip" # .hex, .zip to be specified
      FIRMWARE_FILE: "/firmware.hex" # .hex, .zip to be specified
    volumes:
       #- "./beta/CC1352P2_CC2652P_launchpad_coordinator_xxx.hex:/firmware.hex" # .hex to be specified
       - "./stable/CC1352P2_CC2652P_launchpad_coordinator_20230922.hex:/firmware.hex" # .hex to be specified
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: [ "-ewv", "-p", "/dev/ttyUSB0" ] # "--bootloader-sonoff-usb" required for Sonoff Dongle-P only
``` 

Any idea what I am doing wrong ?

**Comment by git-developer** [comment]
Thr message means that the device is not responding. This may have different causes, e.g.
- another process has opened the device
- the bootloader is locked
- a hardware issue

See similar open issue https://github.com/JelmerT/cc2538-bsl/issues/63 and other [closed](https://github.com/JelmerT/cc2538-bsl/issues?q=Timeout+waiting+for+ACK%2FNACK+after+%27Synch+%280x55+0x55%29%27+is%3Aclosed) issues.

This is probably not related to this project which just adds the Docker part.

**Comment by chris-1243** [comment]
Thanks for the possible causes.

I guess my bootloader is locked as the device is perfectly working.

**Comment by git-developer** [comment]
You're welcome!

**Comment by chris-1243** [comment]
Definitely a bootloader issue.

I had to open my stick and press the boot button at the same time as I plugged the dongle then release it...

**Comment by git-developer** [comment]
Have you been able to flash your stick successfully using this procedure?

**Comment by chris-1243** [comment]
Yes, I successfully flashed it.

**Comment by git-developer** [comment]
Great, congratulations! Case closed :)
