### ISSUE TITLE
port: invalid int value

### ISSUE THREAD

**Issue by chris-1243** [git-developer/ti-cc-tool#8]
I just pulled the latest docker image and when I am running the container I get such error:
```
Attaching to ti-cc-tool-1
ti-cc-tool-1  | Firmware file:   '/firmware.hex'
ti-cc-tool-1  | usage: cc2538-bsl.py [-h] [-q] [-V] [-f] [-e] [-E ERASE_PAGE] [-w] [-W] [-v]
ti-cc-tool-1  |                      [-r] [-l LEN] [-p PORT] [-b BAUD] [-a ADDRESS]
ti-cc-tool-1  |                      [-i IEEE_ADDRESS] [--bootloader-active-high]
ti-cc-tool-1  |                      [--bootloader-invert-lines] [--bootloader-sonoff-usb]
ti-cc-tool-1  |                      [-D] [--version]
ti-cc-tool-1  |                      file
ti-cc-tool-1  | cc2538-bsl.py: error: argument -p/--port: invalid int value: '/dev/ttyUSB0'
ti-cc-tool-1 exited with code 2
``` 

I revert to the previous image (2024-01-28) and with the same `docker-compose.yaml` evertyhing is working fine. Any idea what has changed. I checked your github readme and strictly followed your example and got the error above as well

**Comment by git-developer** [comment]
Thanks for your report. This is an open upstream issue discussed in https://github.com/JelmerT/cc2538-bsl/issues/161. As soon as it is solved, I can integrate the fix into the docker image.

**Comment by git-developer** [comment]
The issue is fixed and the image is updated.
