### ISSUE TITLE
 Unreadable firmware

### ISSUE THREAD

**Issue by drbartek** [git-developer/ti-cc-tool#9]
I am trying to flash this firmware:
https://github.com/Koenkk/Z-Stack-firmware/discussions/496

but without success:

root@xxx:/docker/ti-cc-tool# docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 -e FIRMWARE_FILE=CC1352P2_CC2652P_launchpad_coordinator_20240315.zip ckware/ti-cc-tool -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb
ERROR: Unreadable firmware file 'CC1352P2_CC2652P_launchpad_coordinator_20240315.zip'

the same happens with other versions 

thx

**Comment by git-developer** [comment]
Your're facing two problems:
* Flashing a zip archive is only supported for archives containing a single file.
* You're not mounting your local file into the container.

Fix:
1. Download the archive to your local filesystem and extract the firmware file `CC1352P2_CC2652P_launchpad_coordinator_20240315.hex`
2. Mount the firmware file into the container:
    `$ docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 -v CC1352P2_CC2652P_launchpad_coordinator_20240315.hex:/firmware.hex -e FIRMWARE_FILE=/firmware.hex ckware/ti-cc-tool -ewv -p /dev/ttyUSB0 --bootloader-sonoff-usb`

**Comment by drbartek** [comment]
further unfortunately it does not work

I also tried with 'docker-compose' (zip contains only one file) and it is also the same.
I'm not doing this for the first time before it worked and now unfortunately not :-(

  ti-cc-tool:
    container_name: ti-cc-tool
    image: "ckware/ti-cc-tool"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      FIRMWARE_FILE: "/firmware.zip"
    volumes:
      - "/docker/ti-cc-tool/CC1352P2_CC2652P_launchpad_coordinator_20240315.zip:/firmware.zip"
    command: [ "-ewv", "-p", "/dev/ttyUSB0", "--bootloader-sonoff-usb" ]

_Creating ti-cc-tool ... done
Attaching to ti-cc-tool
ti-cc-tool    | ERROR: Unreadable firmware file '/firmware.zip'
ti-cc-tool exited with code 1_

**Comment by git-developer** [comment]
This error message means that the local file does not exist or is not readable.

Please follow the steps of my previous message (download, extract, add mount argument). If the error still occurs, post your command with output and the output of `ls -la`.

**Comment by drbartek** [comment]
ok I fixed 'docker-compose' and it works.
Thanks

**Comment by git-developer** [comment]
You're welcome!
